# Generated by Django 5.1 on 2024-08-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='post.postattachment'),
        ),
    ]
