# Generated by Django 5.1 on 2024-08-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_name'),
        ('account', '0003_alter_user_name_friendshiprequest'),
    ]

    operations = [
    ]
