# Generated by Django 5.1 on 2024-08-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
